### ISSUE TITLE
error converting YAML to JSON:

### ISSUE THREAD

**Issue by anthonyangel** [Scalr/scalr-cli#16]
Hi, when running the CLI I am getting this error when running most commands

```
anthony@penguin:~$ scalr -help create-environment
panic: error converting YAML to JSON: yaml: line 14570: could not find expected ':'

goroutine 1 [running]:
main.loadAPI()
        /home/runner/work/scalr-cli/scalr-cli/main.go:146 +0x4a7
main.printHelpCommand({0x7ffcba822163, 0x12})
        /home/runner/work/scalr-cli/scalr-cli/help.go:112 +0x3e
main.printHelp()
        /home/runner/work/scalr-cli/scalr-cli/help.go:44 +0x110
main.main()
        /home/runner/work/scalr-cli/scalr-cli/main.go:100 +0x51c
anthony@penguin:~$ scalr -version
0.9.0
anthony@penguin:~$ 
```

**Comment by anthonyangel** [comment]
This is working now. I would assume that the API spec which the CLI pulled down was invalid and that has since been sorted
